### ISSUE TITLE
Не уменьшается баланс при вызове метода "pay".

### ISSUE THREAD

**Issue by DmitryZolotov** [DmitryZolotov/java_team_project#1]
# Описание
При вызове метода "pay" не происходит уменьшение суммы начального баланса.

# Локация дефекта
Класс: "CreditAccount";
Метод: "pay".
https://github.com/DmitryZolotov/java_team_project/blob/0aeae931153e45a996bfd00b7e3d294c8b89e2d7/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L40

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/DmitryZolotov/java_team_project/blob/credit/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java) в IDEA;
2. В тестовом классе "CreditAccountTest" создать объект класса "CreditAccount";
3. Указать значение параметра "initialBalance" 7_000;
4. Указать значение параметра "creditLimit" 5_000;
5. Указать значение параметра "rate" 15;
5. Для объекта класса "CreditAccount" вызвать метод "pay" со значением 1_000;
6. Создать тест "Assertions.assertEquals" с аргументами (6_000, account.getBalance());
7. Запустить тест;
8. Ознакомиться с результатом теста.

*Ожидаемый результат:* Тест проходит, баланс уменьшается на 1_000 и становится 6_000.
*Фактический результат:* Тест не проходит, баланс становится равным -1_000.

# Выполненный тест
Тестовый класс: "CreditAccountTest";
Тест: "shouldDecreasedBalance".

# Скриншоты
![Screenshot_8](https://github.com/DmitryZolotov/java_team_project/assets/147493873/797b44ab-6b1d-414e-af93-1d38036e5354)
![Screenshot_9](https://github.com/DmitryZolotov/java_team_project/assets/147493873/e68329a9-6bd8-40a5-a2fc-84214ce521c1)

# Окружение
* **Операционная система:** Windows 7
* **IDEA:** IntelliJ IDEA 2018.2.8 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Smytstone** [comment]
Метод доработан и соответствует тз
