### ISSUE TITLE
У конструктора "CreditAccount" отсутствует исключение "IllegalArgumentException" на значение кредитного лимита, равное нулю.

### ISSUE THREAD

**Issue by DmitryZolotov** [DmitryZolotov/java_team_project#11]
# Описание
У конструктора "CreditAccount" отсутствует исключение "IllegalArgumentException" на значение кредитного лимита, равное нулю.
creditLimit не может быть равно нулю.

# Локация дефекта
Класс: "CreditAccount";
Конструктор: "CreditAccount".
https://github.com/DmitryZolotov/java_team_project/blob/0aeae931153e45a996bfd00b7e3d294c8b89e2d7/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L19

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/DmitryZolotov/java_team_project/blob/credit/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java) в IDEA;
2. В тестовом классе "CreditAccountTest" создать объект класса "CreditAccount";
3. Указать значение параметра "initialBalance" 2_000;
4. Указать значение параметра "creditLimit" 0;
5. Указать значение параметра "rate" 15;
6. Создать тест "Assertions.assertThrows";
7. Запустить тест;
8. Ознакомиться с результатом теста.

*Ожидаемый результат:* Тест проходит, в консоль выводится сообщение:
"Лимит по кредиту не может быть равен нулю, а у Вас: 0".
*Фактический результат:* Тест не проходит, в консоль выводится сообщение: 
Expected java.lang.IllegalArgumentException to be thrown, but nothing was thrown.

# Выполненный тест
Тестовый класс: "CreditAccountTest";
Тест: "shouldExceptIfCreditLimitNegative".

# Скриншоты
![Screenshot_16](https://github.com/DmitryZolotov/java_team_project/assets/147493873/151925d9-1dc8-4624-8643-32faf210d091)
![Screenshot_17](https://github.com/DmitryZolotov/java_team_project/assets/147493873/1fade5ff-a514-406b-a95e-8ac11d639871)

# Окружение
* **Операционная система:** Windows 7
* **IDEA:** IntelliJ IDEA 2018.2.8 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Smytstone** [comment]
Добавлено исключение в конструктор класса CreditAccount
