### ISSUE TITLE
У конструктора "CreditAccount" отсутствует исключение "IllegalArgumentException" на отрицательное значение начального баланса.

### ISSUE THREAD

**Issue by DmitryZolotov** [DmitryZolotov/java_team_project#12]
# Описание
У конструктора "CreditAccount" отсутствует исключение "IllegalArgumentException" на отрицательное значение начального баланса.
initialBalance - неотрицательное число.

# Локация дефекта
Класс: "CreditAccount";
Конструктор: "CreditAccount".
https://github.com/DmitryZolotov/java_team_project/blob/0aeae931153e45a996bfd00b7e3d294c8b89e2d7/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L19

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/DmitryZolotov/java_team_project/blob/credit/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java) в IDEA;
2. В тестовом классе "CreditAccountTest" создать объект класса "CreditAccount";
3. Указать значение параметра "initialBalance" -2_000;
4. Указать значение параметра "creditLimit" 1_000;
5. Указать значение параметра "rate" 15;
6. Создать тест "Assertions.assertThrows";
7. Запустить тест;
8. Ознакомиться с результатом теста.

*Ожидаемый результат:* Тест проходит, в консоль выводится сообщение:
"Начальный баланс не может быть отрицательным, а у Вас: -2_000".
*Фактический результат:* Тест не проходит, в консоль выводится сообщение: 
Expected java.lang.IllegalArgumentException to be thrown, but nothing was thrown.

# Выполненный тест
Тестовый класс: "CreditAccountTest";
Тест: "shouldExceptIfInitialBalanceNegative".

# Скриншоты
![Screenshot_20](https://github.com/DmitryZolotov/java_team_project/assets/147493873/cde91f37-2470-461f-956b-14c97766b68a)
![Screenshot_21](https://github.com/DmitryZolotov/java_team_project/assets/147493873/430c682e-2d51-495e-8b47-07245dfc567d)

# Окружение
* **Операционная система:** Windows 7
* **IDEA:** IntelliJ IDEA 2018.2.8 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Smytstone** [comment]
Добавлено исключение в конструктор класса CreditAccount
