### ISSUE TITLE
Не обрабатывается исключение класса IllegalArgumentException если минимальный баланс больше максимального баланса. 

### ISSUE THREAD

**Issue by Smytstone** [DmitryZolotov/java_team_project#2]
# Описание
При создании объекта класса SavingAccount с минимальным балансом больше максимального, не обрабатывается исключение IllegalArgumentException.

# Локация дефекта
https://github.com/DmitryZolotov/java_team_project/blob/2411c5ce8af6cc6303ac0ac8017c6987bdada67b/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22

# Шаги воспроизведения 

1. Открыть [код программы](https://github.com/DmitryZolotov/java_team_project/blob/saving/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java) в IDEA
2. Создать тест Assertions.assertThrows
3. Создать объект класса "SavingAccount"
4. Вставить значение поля  'minBalance' 20_000.
5. Вставить значение поля  'maxBalance' 10_000.
6. Посмотреть на результат в консоли

*Ожидаемый результат:*  Тест выполнится 
*Фактический результат:* Тест не проходит, в консоль выводится информация: Expected java.lang.IllegalArgumentException to be thrown, but nothing was thrown.

# Скриншот
![1](https://github.com/DmitryZolotov/java_team_project/assets/147393251/d8ea7578-682e-4c98-a179-6e1c916ad3e1)

# Окружение
* **Операционная система:** Windows 11
* **IDE:** IntelliJ IDEA Community Edition 2023.3.4
* **Java:** OpenJDK 11

**Comment by DmitryZolotov** [comment]
Добавлено исключение для случая, при котором минимальный баланс больше максимального баланса.

![Screenshot_6](https://github.com/DmitryZolotov/java_team_project/assets/147493873/8e80b448-95f1-435e-97e6-23474d9eb165)
