### ISSUE TITLE
Не обрабатывается исключение класса IllegalArgumentException если минимальный баланс отрицательный.

### ISSUE THREAD

**Issue by Smytstone** [DmitryZolotov/java_team_project#3]
# Описание
При создании объекта класса SavingAccount с отрицательным минимальным балансом , не обрабатывается исключение IllegalArgumentException.

# Локация дефекта
https://github.com/DmitryZolotov/java_team_project/blob/2411c5ce8af6cc6303ac0ac8017c6987bdada67b/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22

# Шаги воспроизведения 
1. Открыть [код программы](https://github.com/DmitryZolotov/java_team_project/blob/saving/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java) в IDEA
2. Создать тест Assertions.assertThrows
3. Создать объект класса "SavingAccount"
4. Вставить значение поля  'minBalance' -20_000.
5. Посмотреть на результат в консоли

*Ожидаемый результат:*  Тест выполнится 
*Фактический результат:* Тест не проходит, в консоль выводится информация: Expected java.lang.IllegalArgumentException to be thrown, but nothing was thrown.

# Скриншот
![2](https://github.com/DmitryZolotov/java_team_project/assets/147393251/8b6c618b-05cf-431a-bb04-c42d0f564f4b)

# Окружение
* **Операционная система:** Windows 11
* **IDE:** IntelliJ IDEA Community Edition 2023.3.4
* **Java:** OpenJDK 11

**Comment by DmitryZolotov** [comment]
Добавлено исключение для случая, при котором минимальный баланс отрицательный.

![Screenshot_6](https://github.com/DmitryZolotov/java_team_project/assets/147493873/b6ac0b69-ed1a-423a-aeaa-f46da89d63f2)
