### ISSUE TITLE
Не обрабатывается исключение класса IllegalArgumentException если баланс меньше минимального баланса.

### ISSUE THREAD

**Issue by Smytstone** [DmitryZolotov/java_team_project#4]
# Описание
При создании объекта класса SavingAccount с балансом меньше минимального, не обрабатывается исключение IllegalArgumentException.

# Локация дефекта
https://github.com/DmitryZolotov/java_team_project/blob/2411c5ce8af6cc6303ac0ac8017c6987bdada67b/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22

# Шаги воспроизведения 
1. Открыть [код программы](https://github.com/DmitryZolotov/java_team_project/blob/saving/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java) в IDEA
2. Создать тест Assertions.assertThrows
3. Создать объект класса "SavingAccount"
4. Вставить значение поля  'initialBalance' 1_000.
5. Вставить значение поля  'minBalance' 2_000.
6. Посмотреть на результат в консоли

*Ожидаемый результат:*  Тест выполнится 
*Фактический результат:* Тест не проходит, в консоль выводится информация: Expected java.lang.IllegalArgumentException to be thrown, but nothing was thrown.

# Скриншот
![3](https://github.com/DmitryZolotov/java_team_project/assets/147393251/da355274-7f07-44f4-965f-1def41d00773)

# Окружение
* **Операционная система:** Windows 11
* **IDE:** IntelliJ IDEA Community Edition 2023.3.4
* **Java:** OpenJDK 11

**Comment by DmitryZolotov** [comment]
Добавлено исключение для случая, при котором баланс меньше минимального баланса.

![Screenshot_6](https://github.com/DmitryZolotov/java_team_project/assets/147493873/2ce68ebf-c28a-488b-a3c0-3e0d6a2d2253)
