### ISSUE TITLE
Не увеличивается баланс при вызове метода add.

### ISSUE THREAD

**Issue by Smytstone** [DmitryZolotov/java_team_project#5]
# Описание
Метод add класса SavingAccount , не прибавляет сумму к балансу, а перезаписывает его.

# Локация дефекта
https://github.com/DmitryZolotov/java_team_project/blob/2411c5ce8af6cc6303ac0ac8017c6987bdada67b/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L66

# Шаги воспроизведения 
1. Открыть [код программы](https://github.com/DmitryZolotov/java_team_project/blob/saving/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java) в IDEA
2. Создать тест Assertions.assertEquals
3. Создать объект класса "SavingAccount"
4. Вставить значение поля  'initialBalance' 2_000.
5. Вызвать метод add для объекта класса "SavingAccount" c параметром 3_000
6. Посмотреть на результат в консоли

*Ожидаемый результат:*  Тест выполнится, на балансе будет 5_000
*Фактический результат:* Тест не проходит, в консоль выводится информация: AssertionFailedError: Expected :5000 Actual :3000

# Скриншот
![4](https://github.com/DmitryZolotov/java_team_project/assets/147393251/2ac917fe-b033-4f7d-8f70-d05e7cd92fbc)

# Окружение
* **Операционная система:** Windows 11
* **IDE:** IntelliJ IDEA Community Edition 2023.3.4
* **Java:** OpenJDK 11

**Comment by DmitryZolotov** [comment]
Метод "add" отредактирован, прежний тест отрабатывает корректно.

![Screenshot_4](https://github.com/DmitryZolotov/java_team_project/assets/147493873/58ea07ba-9f8b-4d4c-a1c6-e5005a420967)
