### ISSUE TITLE
Баланс становится меньше минимального баланса при вызове метода pay класса SavingAccount.

### ISSUE THREAD

**Issue by Smytstone** [DmitryZolotov/java_team_project#6]
# Описание
Метод pay класса SavingAccount , делает сумму баланса меньше минимального баланса.

# Локация дефекта
https://github.com/DmitryZolotov/java_team_project/blob/2411c5ce8af6cc6303ac0ac8017c6987bdada67b/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L44

# Шаги воспроизведения 
1. Открыть [код программы](https://github.com/DmitryZolotov/java_team_project/blob/saving/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java) в IDEA
2. Создать тест Assertions.assertEquals
3. Создать объект класса "SavingAccount"
4. Вставить значение поля  'initialBalance' 4_000.
5. Вставить значение поля  'minBalance' 1_000.
6. Вызвать метод pay для объекта класса "SavingAccount" c параметром 4_000
7. Посмотреть на результат в консоли

*Ожидаемый результат:*  Тест выполнится, на балансе будет 4_000
*Фактический результат:* Тест не проходит, в консоль выводится информация: AssertionFailedError: Expected :4000 Actual :0

# Скриншот
![5](https://github.com/DmitryZolotov/java_team_project/assets/147393251/690852c0-8c71-4d43-8ec1-0ec9f35a27e7)

# Окружение
* **Операционная система:** Windows 11
* **IDE:** IntelliJ IDEA Community Edition 2023.3.4
* **Java:** OpenJDK 11

**Comment by DmitryZolotov** [comment]
Метод "pay" отредактирован, прежний тест отрабатывает корректно.

![Screenshot_5](https://github.com/DmitryZolotov/java_team_project/assets/147493873/feea7527-3d68-471f-aaa5-1823d79997f8)
