### ISSUE TITLE
Не уменьшается баланс до кредитного лимита при вызове метода "pay".

### ISSUE THREAD

**Issue by DmitryZolotov** [DmitryZolotov/java_team_project#7]
# Описание
При вызове метода "pay" не происходит уменьшение суммы начального баланса до кредитного лимита.

# Локация дефекта
Класс: "CreditAccount";
Метод: "pay".
https://github.com/DmitryZolotov/java_team_project/blob/0aeae931153e45a996bfd00b7e3d294c8b89e2d7/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L40

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/DmitryZolotov/java_team_project/blob/credit/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java) в IDEA;
2. В тестовом классе "CreditAccountTest" создать объект класса "CreditAccount";
3. Указать значение параметра "initialBalance" 7_000;
4. Указать значение параметра "creditLimit" 5_000;
5. Указать значение параметра "rate" 15;
6. Для объекта класса "CreditAccount" вызвать метод "pay" со значением 2_000;
7. Создать тест "Assertions.assertEquals" с аргументами (5_000, account.getBalance());
8. Запустить тест;
9. Ознакомиться с результатом теста.

*Ожидаемый результат:* Тест проходит, баланс уменьшается на 2_000 и становится 5_000.
*Фактический результат:* Тест не проходит, баланс становится равным -2_000.

# Выполненный тест
Тестовый класс: "CreditAccountTest";
Тест: "shouldDecreasedBalanceToLimit".

# Скриншоты
![Screenshot_11](https://github.com/DmitryZolotov/java_team_project/assets/147493873/e86dcd5a-bd91-46bc-9827-517890783d63)
![Screenshot_10](https://github.com/DmitryZolotov/java_team_project/assets/147493873/787e7e93-0693-4495-a98d-63d62f21a398)

# Окружение
* **Операционная система:** Windows 7
* **IDEA:** IntelliJ IDEA 2018.2.8 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Smytstone** [comment]
Метод доработан и соответствует тз
