### ISSUE TITLE
Баланс не остаётся неизменным при его снижении ниже кредитного лимита при вызове метода "pay".

### ISSUE THREAD

**Issue by DmitryZolotov** [DmitryZolotov/java_team_project#8]
# Описание
Баланс не остаётся неизменным при его снижении ниже кредитного лимита при вызове метода "pay".
При снижении баланса ниже кредитного лимита операция должна завершиться, состояние счёта не должно измениться.

# Локация дефекта
Класс: "CreditAccount";
Метод: "pay".
https://github.com/DmitryZolotov/java_team_project/blob/0aeae931153e45a996bfd00b7e3d294c8b89e2d7/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L40

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/DmitryZolotov/java_team_project/blob/credit/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java) в IDEA;
2. В тестовом классе "CreditAccountTest" создать объект класса "CreditAccount";
3. Указать значение параметра "initialBalance" 7_000;
4. Указать значение параметра "creditLimit" 5_000;
5. Указать значение параметра "rate" 15;
6. Для объекта класса "CreditAccount" вызвать метод "pay" со значением 3_000;
7. Создать тест "Assertions.assertEquals" с аргументами (7_000, account.getBalance());
8. Запустить тест;
9. Ознакомиться с результатом теста.

*Ожидаемый результат:* Тест проходит, уменьшение баланса не происходит, его значение по-прежнему остаётся равным 7_000.
*Фактический результат:* Тест не проходит, баланс становится равным -3_000.

# Выполненный тест
Тестовый класс: "CreditAccountTest";
Тест: "shouldDecreasedBalanceToLimit".

# Скриншоты
![Screenshot_12](https://github.com/DmitryZolotov/java_team_project/assets/147493873/09befcb2-3d63-4db6-bf82-fc446ad6bc92)
![Screenshot_13](https://github.com/DmitryZolotov/java_team_project/assets/147493873/5beb79e1-e440-4d92-be86-39a779b728f7)

# Окружение
* **Операционная система:** Windows 7
* **IDEA:** IntelliJ IDEA 2018.2.8 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Smytstone** [comment]
Метод доработан и соответствует тз
