### ISSUE TITLE
Сумма процентов на отрицательный баланс счёта не остаётся равной нулю при положительном балансе при вызове метода "yearChange".

### ISSUE THREAD

**Issue by DmitryZolotov** [DmitryZolotov/java_team_project#9]
# Описание
При положительном балансе на счёте сумма процентов на отрицательный баланс счёта должна оставаться равной нулю.
При выполнении данного теста сумма процентов на отрицательный баланс счёта посчиталась как при отрицательном балансе.

# Локация дефекта
Класс: "CreditAccount";
Метод: "yearChange".
https://github.com/DmitryZolotov/java_team_project/blob/0aeae931153e45a996bfd00b7e3d294c8b89e2d7/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L82

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/DmitryZolotov/java_team_project/blob/credit/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java) в IDEA;
2. В тестовом классе "CreditAccountTest" создать объект класса "CreditAccount";
3. Указать значение параметра "initialBalance" 200;
4. Указать значение параметра "creditLimit" 5_000;
5. Указать значение параметра "rate" 15;
6. Создать тест "Assertions.assertEquals" с аргументами (0, account.yearChange());
7. Запустить тест;
8. Ознакомиться с результатом теста.

*Ожидаемый результат:* Тест проходит, сумма процентов равна 0.
*Фактический результат:* Тест не проходит, сумма процентов равна 30.

# Выполненный тест
Тестовый класс: "CreditAccountTest";
Тест: "shouldShowNumberIfBalancePositive".

# Скриншоты
![Screenshot_14](https://github.com/DmitryZolotov/java_team_project/assets/147493873/f94e7de3-371b-41d5-bdc1-64e2accfbea1)
![Screenshot_15](https://github.com/DmitryZolotov/java_team_project/assets/147493873/9642e406-5c3f-43eb-8647-29d83945d0ea)

# Окружение
* **Операционная система:** Windows 7
* **IDEA:** IntelliJ IDEA 2018.2.8 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Smytstone** [comment]
Метод доработан и соответствует тз
